export const ADD_POLYGON = 'carteModule/ADD_POLYGON'
export const REMOVE_POLYGON = 'carteModule/REMOVE_POLYGON'
export const GET_POLYGONS = 'carteModule/GET_POLYGONS'
export const GET_VARIABLE = 'carteModule/GET_VARIABLE'
export const SET_VARIABLE = 'carteModule/SET_VARIABLE'
export const REMOVE_VARIABLE = 'carteModule/REMOVE_VARIABLE'
export const GET_QUINTILES = 'carteModule/GET_QUINTILES'
export const SET_QUINTILES = 'carteModule/SET_QUINTILES'
export const GET_PALETTE = 'carteModule/GET_PALETTE'
export const SET_PALETTE = 'carteModule/SET_PALETTE'

export const GET_POURCENTAGE = 'carteModule/GET_POURCENTAGE'
export const SET_POURCENTAGE = 'carteModule/SET_POURCENTAGE'

export const GET_REFERENCE_POURCENTAGE = 'carteModule/GET_REFERENCE_POURCENTAGE'
export const SET_REFERENCE_POURCENTAGE = 'carteModule/SET_REFERENCE_POURCENTAGE'